from abc import ABCMeta
from six import add_metaclass
from abc import abstractmethod


@add_metaclass(ABCMeta)
class AbstractProvidesProvenanceData(object):
    """ Indicates that an object provides provenance data
    """

    def __init__(self):
        pass

    @abstractmethod
    def write_provenance_data_in_xml(
            self, file_path, transceiver, message_store, placement=None):
        """ Write the provenance data using XML
        :param file_path: the file path to write the provenance data to
        :param transceiver: the SpinnMan interface object
        :param message_store: the messages generated by the provenance data \
        for a core.
        :param placement: the placement object for this subvertex or None if\
                    the system does not require a placement object
        :return: None
        """
