"""
VertexBasedRoutingInfoAllocator
"""

# pacman imports
from pacman.model.constraints.key_allocator_constraints.\
    key_allocator_contiguous_range_constraint import \
    KeyAllocatorContiguousRangeContraint
from pacman.model.constraints.key_allocator_constraints.\
    key_allocator_fixed_field_constraint import \
    KeyAllocatorFixedFieldConstraint
from pacman.model.constraints.key_allocator_constraints.\
    key_allocator_fixed_key_and_mask_constraint import \
    KeyAllocatorFixedKeyAndMaskConstraint
from pacman.model.constraints.key_allocator_constraints.\
    key_allocator_fixed_mask_constraint import \
    KeyAllocatorFixedMaskConstraint
from pacman.model.constraints.key_allocator_constraints.\
    key_allocator_flexi_field_constraint import \
    KeyAllocatorFlexiFieldConstraint

from pacman.model.routing_info.routing_info import RoutingInfo
from pacman.model.routing_info.subedge_routing_info import SubedgeRoutingInfo
from pacman.model.routing_tables.multicast_routing_tables import \
    MulticastRoutingTables
from pacman.model.routing_info.base_key_and_mask import BaseKeyAndMask

from pacman.utilities import utility_calls
from pacman.utilities.algorithm_utilities import \
    routing_info_allocator_utilities
from pacman import exceptions
from pacman.utilities.utility_objs.field import Field
from pacman.utilities.utility_objs.flexi_field \
    import FlexiField, SUPPORTED_TAGS
# swiped from rig currently.
from pacman.operations.routing_info_allocator_algorithms.\
    field_based_routing_allocator.rigs_bitfield import \
    RigsBitField

# general imports
from enum import Enum
import uuid
import math

# hard coded values
from pacman.utilities.utility_objs.progress_bar import ProgressBar

NUM_BITS_IN_ROUTING = 31
ROUTING_MASK_BIT = 1
APPLICATION_MASK_BIT = 0
START_OF_ROUTING_KEY_POSITION = 0

# the different tyes of field that this system supports
TYPES_OF_FIELDS = Enum(
    value="TYPES_OF_FIELDS",
    names=[("FIXED_MASK", 0),
           ("FIXED_KEY", 1),
           ("FIXED_FIELD", 2)])

# TODO I DONT LIKE THESE BITS
APPLICATION_DIVIDER_FIELD_NAME = "APPLICATION_DIVIDER"
FLEXI_APP_FLAG = "FLEXI_APP_FIELD_VALUE"
FIXED_MASK_APP_FLAG = "FIXED_MASK_APP_FIELD_VALUE"
FIXED_KEY_APP_FLAG = ""
FIXED_MASK_FLAG = "FIXED_MASK"


class VertexBasedRoutingInfoAllocator(object):
    """
    VertexBasedRoutingInfoAllocator
    """

    def __call__(self, partitionable_graph, graph_mapper, subgraph, n_keys_map,
                 routing_paths):
        """

        :param partitionable_graph: The partitionable graph object
        :param graph_mapper: the mapping between the partitionable and
         partitioned graph
        :param subgraph: the partitioned graph
        :param n_keys_map: the mapping between edges and n keys
        :param routing_paths: the routing paths generated by routing
        :return: routing infos objects and the routing tables for the
        spinnaker machine
        """
        progress_bar = ProgressBar(len(subgraph.partitions) * 3,
                                   "Allocating routing keys")

        # ensure groups are stable and correct
        self._determine_groups(subgraph, graph_mapper, partitionable_graph,
                               n_keys_map, progress_bar)

        # define the key space
        bit_field_space = RigsBitField(32)

        # locate however many types of constrants there are
        seen_fields = self._deduce_types(subgraph, progress_bar)

        uses_application_field = False
        if len(seen_fields) > 1:
            self._adds_application_field_to_the_fields(seen_fields)
            uses_application_field = True

        # hack to keep track of a fuck load of bits and peices to get this
        #  shit to work
        # TODO FIX THIS BIT OF HORRIBLE CODE USAGE
        field_mapper = dict()

        # handle the application space
        self._create_application_space_in_the_bit_field_space(
            bit_field_space, seen_fields, field_mapper)

        # assgin fields to positions in the space. if shits going to hit the
        # fan, its here
        bit_field_space.assign_fields()

        # create routing_info_allocator
        routing_info = RoutingInfo()
        routing_tables = MulticastRoutingTables()
        seen_mask_instances = 0

        # extract keys and masks for each edge from the bitfield
        for partition in subgraph.partitions:
            # get keys and masks
            keys_and_masks, seen_mask_instances = \
                self._extract_keys_and_masks_from_bit_field(
                    partition, bit_field_space, n_keys_map,
                    uses_application_field, field_mapper, seen_mask_instances)

            # update routing info for each edge in the partition
            for edge in partition.edges:
                sub_edge_info = SubedgeRoutingInfo(keys_and_masks, edge)
                routing_info.add_subedge_info(sub_edge_info)

                # update routing tables with entries
                routing_info_allocator_utilities.add_routing_key_entries(
                    routing_paths, sub_edge_info, edge, routing_tables)

            # update the progress bar again
            progress_bar.update()
        progress_bar.end()

        return {'routing_infos': routing_info,
                'routing_tables': routing_tables}

    def _adds_application_field_to_the_fields(self, seen_fields):
        """
        tries to determine what the field spaces and values are for the
        application field needed to seperate the differnet hirarchy fields and
        adds it to the fields in current existance.
        :param seen_fields: the types of fields needed to get this simulation
        operating correctly
        :return: None
        """
        required_bits = int(math.ceil(math.log(len(seen_fields), 2)))
        if TYPES_OF_FIELDS.FIXED_KEY.name in seen_fields:
            fixed_keys = seen_fields[TYPES_OF_FIELDS.FIXED_KEY.name]
            # use yield and genrator here

        else:
            if TYPES_OF_FIELDS.FIXED_MASK.name in seen_fields:
                fixed_mask_masks = seen_fields[TYPES_OF_FIELDS.FIXED_MASK.name]
                if len(fixed_mask_masks) > 1:
                    keys = list(fixed_mask_masks.keys)
                    fields = fixed_mask_masks[keys[0]]
                    searching = True
                    bit_generator = \
                        self._generate_bits_that_satisfy_contraints(
                            fields, required_bits)
                    while not searching:
                        searching = True
                    print "AHHH"

                else:
                    keys = list(fixed_mask_masks.keys())
                    fields = fixed_mask_masks[keys[0]]
                    bit_generator = \
                        self._generate_bits_that_satisfy_contraints(
                            fields, required_bits)
                    self._update_first_fixed_mask_field_set(
                        fixed_mask_masks, bit_generator)

    def _update_first_fixed_mask_field_set(
            self, fixed_mask_masks, bit_generator):
        """
        updates the first mask's field set so that it has a applciation field
        with the correct value and the odl fields are adjusted to take into
        account the loss of a number of bits
        :param fixed_mask_masks: the set of fixed mask fields for the first mask
        :param bit_generator: the generator which can provide different sets
        of bits usable for the applciation field
        :return: None
        """
        # get next attempt
        (bit_hi, bit_lo, original_mask) = bit_generator.next()

        # determine value of the application field
        application_field_value = \
            self._determine_fixed_mask_application_field_value(
                original_mask, bit_hi, bit_lo)

        # adjust the fields to reflect new application field scopes
        fields = self._adjust_fixed_mask_fields_for_application_field(
            original_mask, bit_hi, application_field_value)

        # locate the application field bit in the new fields and adjust the
        # tags to be routing, name to APPLICATION_DIVIDER_FIELD_NAME and the
        #  value to the located applciation value
        distance_in_bits = bit_hi - bit_lo
        if distance_in_bits == 1:
            for field in fields:
                if field.hi == bit_hi and field.lo == bit_hi:
                    field.value = application_field_value
                    field.tag = SUPPORTED_TAGS.ROUTING.name
                    field.name = APPLICATION_DIVIDER_FIELD_NAME
        else:
            for field in fields:
                if field.hi == bit_hi and field.lo == bit_lo:
                    field.value = application_field_value
                    field.tag = SUPPORTED_TAGS.ROUTING.name
                    field.name = APPLICATION_DIVIDER_FIELD_NAME

        # update the seen fields object with new fields
        keys = list(fixed_mask_masks.keys())
        fixed_mask_masks[keys[0]] = fields

    def _adjust_fixed_mask_fields_for_application_field(
            self, original_mask, bit_hi, bit_values):
        """
        Takes the old mask and the application feild specs and makes a set
        of new fields to compensate for the placement of the application field
        :param original_mask: the old mask used by the fields
        :param bit_hi: the point where the application space starts
        :param bit_values: the value being used by fixed masks for the
        application field
        :return: the adjusted fields
        """
        value = bit_values << bit_hi
        # invert the mask
        inverted_value = ~value
        # make new mask from inverted and original mask
        new_mask = original_mask & inverted_value
        # convert new mask into fields
        fields = self._convert_mask_into_fields(new_mask)
        # readjust the fields to link to the original mask (needed for mapping
        # later on)
        for field in fields:
            field.value = original_mask
        return fields

    @staticmethod
    def _determine_fixed_mask_application_field_value(mask, bit_hi, bit_lo):
        """
        determines the value of the applciation field for a given mask
        :param mask: the mask to deduce the value for
        :param bit_hi: the bit high index for where the application field
        finsihes
        :param bit_lo: the bit lo index for where the applcation field starts
        :return: the value for the application for this mask
        """
        bit_value = mask >> int(bit_lo)
        mask = int(math.pow((bit_hi - bit_lo), 2))
        bit_value &= mask
        return bit_value

    @staticmethod
    def _generate_bits_that_satisfy_contraints(
            fixed_mask_fields, required_bits):
        """
        generator for getting valid bits from the first fixed mask
        :param fixed_mask_fields: the fields from this fixed mask
        :param required_bits: the number of bits required to match the types
        :type required_bits: int
        :return: the hi and lo bit index for where the region can exist,
         as well as the origianl mask this generator is working on.
        """
        routing_fields = list()

        # locate fields valid for generating collections
        for field in fixed_mask_fields:
            if field.tag == SUPPORTED_TAGS.ROUTING.name:
                routing_fields.append(field)

        # sort fields based on hi
        routing_fields.sort(key=lambda field: field.hi)

        # locate next set of bits to yield to higher function
        for routing_field in routing_fields:
            if routing_field.hi - routing_field.lo >= required_bits:
                current_hi = routing_field.hi
                while (current_hi - required_bits) > routing_field.lo:
                    yield (current_hi, current_hi - required_bits, field.value)
                    current_hi -= 1

    def _extract_keys_and_masks_from_bit_field(
            self, partition, bit_field_space, n_keys_map,
            uses_application_space, field_mapper, seen_mask_instances):
        """
        takes the bit field space and a partition and locates the keys and masks
        for that partition given all its constraints
        :param partition: the partition to extract keys and amsks for
        :param bit_field_space: the bit field space
        :param n_keys_map: the edge to n_keys map
        :param uses_application_space: the bool which states if there is a
        application space being used
        :param seen_mask_instances: a count of how many fixed mask instances
        have been seen, so that it can increment the routing part of the
        fixed mask fields.
        :return: the routing keys and masks for the partition and the number
        of seen fixed masks instances
        """
        routing_keys_and_masks = list()
        application_keys_and_masks = list()
        fixed_key_constraints = utility_calls.locate_constraints_of_type(
            partition.constraints, KeyAllocatorFixedKeyAndMaskConstraint)
        fixed_mask_constraints = utility_calls.locate_constraints_of_type(
            partition.constraints, KeyAllocatorFixedMaskConstraint)
        fixed_field_constraints = utility_calls.locate_constraints_of_type(
            partition.constraints, KeyAllocatorFixedFieldConstraint)
        flexi_field_constraints = utility_calls.locate_constraints_of_type(
            partition.constraints, KeyAllocatorFlexiFieldConstraint)
        continious_constraints = utility_calls.locate_constraints_of_type(
            partition.constraints, KeyAllocatorContiguousRangeContraint)

        if len(fixed_key_constraints) > 0:
            print "ah"
        elif len(fixed_mask_constraints) > 0:
            # get constraint and its fields
            fixed_mask_constraint_mask = fixed_mask_constraints[0].mask
            fixed_mask_fields = field_mapper[
                "{}:{}".format(FIXED_MASK_FLAG, fixed_mask_constraint_mask)]
            fixed_mask_app_field_value = \
                field_mapper["{}".format(FIXED_MASK_APP_FLAG)]
            # trakcer for iterator fields
            range_based_fixed_mask_fields = list()

            # add the app field (must exist in this situation)
            inputs = dict()
            inputs [APPLICATION_DIVIDER_FIELD_NAME] = fixed_mask_app_field_value

            # handle the inotus for static parts of the mask
            for fixed_mask_field in fixed_mask_fields:
                app_field_space = bit_field_space(**inputs)
                tag = list(app_field_space.get_tags(
                    "{}".format(fixed_mask_field)))[0]
                if tag == SUPPORTED_TAGS.ROUTING.name:
                    inputs["{}".format(fixed_mask_field)] = seen_mask_instances
                else:
                    range_based_fixed_mask_fields.append(fixed_mask_field)

            if len(range_based_fixed_mask_fields) > 1:
                raise exceptions.PacmanConfigurationException(
                    "Im not designed to work with multiple ranged based "
                    "fields for a fixed mask. please fix and try again")

            # get n keys from n_keys_map for the range based mask part
            n_keys = n_keys_map.n_keys_for_partitioned_edge(partition.edges[0])

            # generate keys
            for key_index in range(0, n_keys):
                inputs["{}".format(range_based_fixed_mask_fields[0])] = \
                    key_index
                # routing keys and masks
                routing_key = bit_field_space(**inputs).get_value(
                    tag=SUPPORTED_TAGS.ROUTING.name)
                routing_mask = bit_field_space(**inputs).get_mask(
                    tag=SUPPORTED_TAGS.ROUTING.name)
                routing_keys_and_masks.append(BaseKeyAndMask(routing_key,
                                                             routing_mask))

                # application keys and masks
                application_key = bit_field_space(**inputs).get_value(
                    tag=SUPPORTED_TAGS.APPLICATION.name)
                application_mask = bit_field_space(**inputs).get_mask(
                    tag=SUPPORTED_TAGS.APPLICATION.name)
                application_keys_and_masks.append(BaseKeyAndMask(
                    application_key, application_mask))

            # update the seen mask instances so the next one gets a new key
            seen_mask_instances += 1

        elif len(fixed_field_constraints) > 0:
            print "ah3"
        elif len(flexi_field_constraints) > 0:
            inputs = dict()

            # if theres a application field, add the value
            if uses_application_space:
                inputs[APPLICATION_DIVIDER_FIELD_NAME] = \
                    field_mapper["{}:{}".format(
                        FLEXI_APP_FLAG,
                        flexi_field_constraints[0].fields[0].name)]

            # collect flexi fields by group
            range_based_fixed_mask_fields = list()
            for field in flexi_field_constraints[0].fields:
                if field.value is not None:
                    inputs[field.name] = field.value
                else:
                    range_based_fixed_mask_fields.append(field)

            # if the set contains a ranfe_based felxi field do search
            if len(range_based_fixed_mask_fields) != 0:
                routing_keys_and_masks, application_keys_and_masks = \
                    self._handle_set_of_flexi_range_fields(
                        range_based_fixed_mask_fields, bit_field_space,
                        routing_keys_and_masks, application_keys_and_masks,
                        inputs, 0)

            else:  # no range, just grab the key and value
                key = bit_field_space(**inputs).get_value()
                mask = bit_field_space(**inputs).get_mask()
                routing_keys_and_masks.append(BaseKeyAndMask(key, mask))

        # if theres a continious constraint check, check the keys for
        # continiouity
        if len(continious_constraints) != 0:
            are_continious = self._check_keys_are_continious(
                application_keys_and_masks)
            if not are_continious:
                raise exceptions.PacmanConfigurationException(
                    "These keys returned from the bitfield are"
                    "not continous. Therefore cannot be used")

            # if continious, we only need the first key, so drop the rest
            routing_keys_and_masks = routing_keys_and_masks[0]

        # return keys and masks
        return routing_keys_and_masks, seen_mask_instances

    @staticmethod
    def _check_keys_are_continious(keys_and_masks):
        """
        searches though the keys and masks and checks if they are all continous

        :param keys_and_masks: the keys to check if they are continious
        :return: true if they are continious, false otherwise
        """
        last_key = None
        for keys_and_mask in keys_and_masks:
            if last_key is None:
                last_key = keys_and_mask.key
            else:
                if last_key + 1 != keys_and_mask.key:
                    return False
                last_key = keys_and_mask.key
        return True

    def _handle_set_of_flexi_range_fields(
            self, range_based_flexi_fields, bit_field_space,
            routing_keys_and_masks, application_keys_and_masks, inputs,
            position):
        """
        takes a set of flexi fields which are range based and deduces the
        routing keys and masks for the set
        :param range_based_flexi_fields: the set of range based flexi fields
        :param bit_field_space: the bit field space
        :param routing_keys_and_masks: set of routing keys and masks built from
        previous iterations
        :param application_keys_and_masks: the application keys and masks from
        prvious iterations
        :param inputs: parameters used by the bit field to get keys
        :param position: the position within the set (used for exit condition)
        :return: routing keys and application keys for the flexi field set
        """

        for value in range(0,
                           range_based_flexi_fields[position].instance_n_keys):
            inputs[range_based_flexi_fields[position].name] = value
            if position < len(range_based_flexi_fields):
                # routing keys and masks
                routing_key = bit_field_space(**inputs).get_value(
                    tag=SUPPORTED_TAGS.ROUTING.name)
                routing_mask = bit_field_space(**inputs).get_mask(
                    tag=SUPPORTED_TAGS.ROUTING.name)
                routing_keys_and_masks.append(BaseKeyAndMask(routing_key,
                                                             routing_mask))

                # application keys and masks
                application_key = bit_field_space(**inputs).get_value(
                    tag=SUPPORTED_TAGS.APPLICATION.name)
                application_mask = bit_field_space(**inputs).get_mask(
                    tag=SUPPORTED_TAGS.APPLICATION.name)
                application_keys_and_masks.append(BaseKeyAndMask(
                    application_key, application_mask))
            else:

                # not at the end, keep iterating but add the results from
                # the iterations before going back upwards
                position += 1
                other_routing_keys_and_masks, \
                    other_application_keys_and_masks = \
                    self._handle_set_of_flexi_range_fields(
                        range_based_flexi_fields, bit_field_space,
                        routing_keys_and_masks, application_keys_and_masks,
                        inputs, position)

                # add keys before going upwards
                routing_keys_and_masks.extend(other_routing_keys_and_masks)
                application_keys_and_masks.extend(
                    other_application_keys_and_masks)

        # exit this iteration
        return routing_keys_and_masks, application_keys_and_masks

    def _create_application_space_in_the_bit_field_space(
            self, bit_field_space, fields, field_mapper):
        """
        takes the fields seen and adjusted for bitfield and the bitfueidl
        object and builds the fields for being assigned to kys and masks
        :param bit_field_space: th bit field space
        :param fields: the fields which have been adjusted accordingly to
        work in the bit field scope
        :param field_mapper: mapper between numerious bits and pieces
        :return:
        """
        # locate the application field if it exists
        application_field, application_field_spare_values = \
            self._locate_application_field(fields)

        # create the application basd field if its not none
        if application_field is not None:
            length = application_field.hi - application_field.lo
            if length == 0:
                length = 1
            bit_field_space.add_field(
                application_field.name, length, application_field.lo,
                tags=SUPPORTED_TAGS.ROUTING.name)

        # iterate though the fields, adding fields to the system
        for field in fields:
            # handle fixed mask fields
            if field == TYPES_OF_FIELDS.FIXED_MASK.name:
                fixed_fields = fields[TYPES_OF_FIELDS.FIXED_MASK.name]
                for fixed_field_key in fixed_fields:

                    # create the top level bt field space for this set
                    fixed_feild_list = fixed_fields[fixed_field_key]
                    fixed_field_application_field = self._locate_field_by_name(
                        fixed_feild_list, APPLICATION_DIVIDER_FIELD_NAME)
                    internal_field_space = self._create_internal_field_space(
                        bit_field_space, fixed_field_application_field.value,
                        fixed_field_application_field)

                    # iterate though rest of the fields adding them to the
                    #  lower position field space
                    for fixed_field in fixed_feild_list:
                        if fixed_field.name != APPLICATION_DIVIDER_FIELD_NAME:
                            length = fixed_field.hi - fixed_field.lo
                            if length == 0:
                                length = 1
                            internal_field_space.add_field(
                                "{}".format(fixed_field.name), length,
                                fixed_field.lo, fixed_field.tag)
                            key = "{}:{}".format(
                                FIXED_MASK_FLAG, fixed_field.value)
                            if key not in field_mapper:
                                field_mapper[key] = list()
                            field_mapper[key].append(fixed_field.name)
                        else:
                            field_mapper[FIXED_MASK_APP_FLAG] = \
                                fixed_field.value

            # hnadle fixed field
            elif field == TYPES_OF_FIELDS.FIXED_FIELD.name:
                # TODO need to check this bit out
                for fixed_field in fields[TYPES_OF_FIELDS.FIXED_FIELD.name]:
                    fields_data = \
                        self._convert_mask_into_fields(fixed_field.mask)
                    for (position, length) in fields_data:
                        random_identifer = uuid.uuid4()
                        field_mapper[fixed_field] = random_identifer
                        bit_field_space.add_field(
                            random_identifer, length, position)

            # handle fixed key fields
            elif field == TYPES_OF_FIELDS.FIXED_KEY.name:
                # TODO need to check this bit out
                for key_and_mask in fields[TYPES_OF_FIELDS.FIXED_KEY.name]:
                    random_identifer = uuid.uuid4()
                    bit_field_space.add_field(
                        random_identifer, NUM_BITS_IN_ROUTING, 0)
                    field_mapper[key_and_mask] = random_identifer
                    # set the value for the field
                    inputs = dict()
                    inputs[random_identifer] = key_and_mask.key
                    bit_field_space(**inputs)

            else:  # handle flexi field stuff
                if application_field is not None:

                    # create a new bit field where everyhting is linked off a
                    # sub internal app field
                    internal_value = application_field_spare_values[0]
                    application_field_spare_values.remove(internal_value)
                    internal_bit_field_space = \
                        self._create_internal_field_space(
                            bit_field_space, internal_value, application_field)
                    field_mapper["{}:{}".format(FLEXI_APP_FLAG, field)] = \
                        internal_value

                    # handle the flexi fields
                    self._create_flexi_field_space_in_the_bit_field_space(
                        internal_bit_field_space, field, fields)
                else:
                    self._create_flexi_field_space_in_the_bit_field_space(
                        bit_field_space, field, fields)

    def _locate_application_field(self, fields):
        """
        searches through the fields looking for the application field, and
        when its found, deduces whats left for space space for other fields
        :param fields: the set of field types and the fields
        :return: the application field and the spare values of the field
        """
        application_feild = None
        application_field_spare_values = None
        # search for the field with the correct tag
        for field in fields:
            # if a fixed mask field, locate correct application field and value
            if field == TYPES_OF_FIELDS.FIXED_MASK.name:
                fixed_fields = fields[TYPES_OF_FIELDS.FIXED_MASK.name]
                for fixed_field_key in fixed_fields:
                    fixed_feild_list = fixed_fields[fixed_field_key]
                    for fixed_field in fixed_feild_list:
                        # if the field is the correct field, mark and deduce
                        # usable values
                        if fixed_field.name == APPLICATION_DIVIDER_FIELD_NAME:
                            if application_feild is None:
                                application_feild = fixed_field
                                application_field_spare_values = \
                                    self._deduce_application_field_space(
                                        application_feild)
                            else:
                                application_field_spare_values.remove(
                                    fixed_field.value)
            elif field == TYPES_OF_FIELDS.FIXED_KEY.name:
                # TODO NEED TO COMPLETE THIS BIT
                pass
            elif field == TYPES_OF_FIELDS.FIXED_FIELD.name:
                # TODO NEED TO COMPLETE THIS BIT
                pass
        return application_feild, application_field_spare_values

    @staticmethod
    def _deduce_application_field_space(application_feild):
        """
        given a application field, deduces the spare spaces avilable to it
        :param application_feild: the application field in question
        :return: the spare values
        """

        # get length of field
        length = application_feild.hi - application_feild.lo
        application_field_spare_values = list()
        # if the length is zero, tis becuase its actually one bit, but the
        #  mask to field builder makes length of 1 into the same value here,
        # TODO might be worth seeing if that can be solved
        if length == 0:
            length = 1

        # build avilable values
        for value in range(0, ((2 ^ length) -1)):
            application_field_spare_values.append(value)

        # remove the one this application field is built from
        application_field_spare_values.remove(application_feild.value)
        return application_field_spare_values

    def _create_flexi_field_space_in_the_bit_field_space(
            self, bit_field_space, field, fields):
        """
        creates the fields in the bit field space for the flexi fields
        :param bit_field_space: the bit field space
        :param field: the field that needs placing into the bitfield space
        :param fields: ???????
        :return: None
        """
        # field must be a flexi field, work accordingly
        example_entry = self._check_entries_are_tag_consistent(fields, field)
        if example_entry.tag is None:
            bit_field_space.add_field(field)
        else:
            bit_field_space.add_field(field, tags=example_entry.tag)

        for field_instance in fields[field]:
            # only carry on if theres more to create
            if len(fields[field][field_instance]) > 0:

                # create next level
                internal_bit_field = self._create_internal_field_space(
                    bit_field_space, field_instance.value, field_instance)

                # deal with next level hirarckhy
                for nested_field in fields[field][field_instance]:
                    self._create_flexi_field_space_in_the_bit_field_space(
                        internal_bit_field, nested_field,
                        fields[field][field_instance])

            # bottom level
            if field_instance.instance_n_keys is not None:
                for value in range(0, field_instance.instance_n_keys):
                    self._create_internal_field_space(
                        bit_field_space, value, field_instance)

    @staticmethod
    def _check_entries_are_tag_consistent(fields, field):
        """
        checks that the tags of the fields are consistent with each other
        :param fields: the set of fields which could have tags
        :param field: field its comparing against
        :return: the first field
        """
        first = None
        for field_instance in fields[field]:
            if first is None:
                first = field_instance
            elif field_instance.tag != first.tag:
                raise exceptions.PacmanConfigurationException(
                    "Two fields with the same id, but with different tags. "
                    "This is deemed an error and therefore please fix before"
                    "trying again. thanks you")
        return first

    @staticmethod
    def _convert_mask_into_fields(entity):
        """

        :param entity:
        :return:
        """
        results = list()
        expanded_mask = utility_calls.expand_to_bit_array(entity)
        # set up for first location
        detected_change = True
        detected_change_position = NUM_BITS_IN_ROUTING
        detected_last_state = expanded_mask[NUM_BITS_IN_ROUTING]
        # iterate up the key looking for fields
        for position in range(NUM_BITS_IN_ROUTING - 1,
                              START_OF_ROUTING_KEY_POSITION - 2, -1):
            # check for last bit iteration
            if position == -1:
                # if last bit has changed, create new field
                if detected_change_position != position:

                    # create field with correct routing tag
                    if detected_last_state == ROUTING_MASK_BIT:
                        results.append(Field(
                            NUM_BITS_IN_ROUTING - detected_change_position,
                            NUM_BITS_IN_ROUTING, entity,
                            SUPPORTED_TAGS.ROUTING.name))
                    else:
                        results.append(Field(
                            NUM_BITS_IN_ROUTING - detected_change_position,
                            NUM_BITS_IN_ROUTING, entity,
                            SUPPORTED_TAGS.APPLICATION.name))
            else:
                # check for bit iteration
                if expanded_mask[position] != detected_last_state:
                    # if changed state, a field needs to be created. check for
                    # which type of field to support
                    if detected_last_state == ROUTING_MASK_BIT:
                        results.append(Field(
                            NUM_BITS_IN_ROUTING - detected_change_position,
                            NUM_BITS_IN_ROUTING - (position + 1),
                            entity, SUPPORTED_TAGS.ROUTING.name))
                    else:
                        results.append(Field(
                            NUM_BITS_IN_ROUTING - detected_change_position,
                            NUM_BITS_IN_ROUTING - (position + 1),
                            entity, SUPPORTED_TAGS.APPLICATION.name))
                    # update positions
                    detected_last_state = expanded_mask[position]
                    detected_change_position = position
        return results

    def _deduce_types(self, subgraph, progress_bar):
        """
        deducing the number of applications required for this key space
        :param subgraph:
        :param progress_bar:
        :return:
        """
        seen_fields = dict()
        known_fields = list()
        for partition in subgraph.partitions:
            for constraint in partition.constraints:
                if not isinstance(constraint,
                                  KeyAllocatorContiguousRangeContraint):
                    if isinstance(constraint, KeyAllocatorFlexiFieldConstraint):
                        self._handle_flexi_field(
                            constraint, seen_fields, known_fields)
                    if isinstance(constraint,
                                  KeyAllocatorFixedKeyAndMaskConstraint):
                        if TYPES_OF_FIELDS.FIXED_KEYS.name not in seen_fields:
                            seen_fields[TYPES_OF_FIELDS.FIXED_KEYS.name] = \
                                list()
                        for key_mask in constraint.keys_and_masks:
                            seen_fields[TYPES_OF_FIELDS.FIXED_KEYS.name].\
                                append(key_mask)
                    if isinstance(constraint, KeyAllocatorFixedMaskConstraint):
                        fields = self._convert_mask_into_fields(constraint.mask)
                        if TYPES_OF_FIELDS.FIXED_MASK.name not in seen_fields:
                            seen_fields[TYPES_OF_FIELDS.FIXED_MASK.name] =\
                                dict()
                        for field in fields:
                            if field.value not in seen_fields[
                                    TYPES_OF_FIELDS.FIXED_MASK.name]:
                                # add a new list for this mask type
                                seen_fields[
                                    TYPES_OF_FIELDS.FIXED_MASK.name][
                                    field.value] = list()
                            if field not in seen_fields[
                                    TYPES_OF_FIELDS.FIXED_MASK.name][
                                    field.value]:
                                seen_fields[
                                    TYPES_OF_FIELDS.FIXED_MASK.name][
                                    field.value].append(field)

                    if isinstance(constraint, KeyAllocatorFixedFieldConstraint):
                        if TYPES_OF_FIELDS.FIXED_FIELD not in seen_fields:
                            seen_fields[TYPES_OF_FIELDS.FIXED_FIELD.name] = \
                                list()
                        seen_fields[TYPES_OF_FIELDS.FIXED_FIELD.name].\
                            append(constraint.fields)

            # update the progress bar
            progress_bar.update()
        return seen_fields

    def _determine_groups(self, subgraph, graph_mapper, partitionable_graph,
                          n_keys_map, progress_bar):
        """

        :param subgraph:
        :param graph_mapper:
        :param partitionable_graph:
        :param n_keys_map:
        :return:
        """

        routing_info_allocator_utilities.check_types_of_edge_constraint(
            subgraph)

        for partition in subgraph.partitions:
            fixed_key_constraints = \
                utility_calls.locate_constraints_of_type(
                    partition.constraints,
                    KeyAllocatorFixedKeyAndMaskConstraint)
            fixed_mask_constraints = \
                utility_calls.locate_constraints_of_type(
                    partition.constraints,
                    KeyAllocatorFixedMaskConstraint)
            fixed_field_constraints = \
                utility_calls.locate_constraints_of_type(
                    partition.constraints,
                    KeyAllocatorFixedFieldConstraint)

            if (len(fixed_key_constraints) == 0
                    and len(fixed_mask_constraints) == 0
                    and len(fixed_field_constraints) == 0):
                self._add_field_constraints(
                    partition, graph_mapper, partitionable_graph, n_keys_map)
            progress_bar.update()

    @staticmethod
    def _handle_flexi_field(constraint, seen_fields, known_fields):
        """

        :param constraint:
        :param seen_fields:
        :param known_fields:
        :return:
        """
        # set the level of search
        current_level = seen_fields
        for constraint_field in constraint.fields:
            found_field = None

            # try to locate field in level
            for seen_field in current_level:
                if constraint_field.name == seen_field:
                    found_field = seen_field

            # seen the field before but not at this level. error
            if found_field is None and constraint_field in known_fields:
                raise exceptions.PacmanConfigurationException(
                    "Cant find the field {} in the expected position"
                        .format(constraint_field))

            # if not seen the field before
            if found_field is None and constraint_field.name not in known_fields:
                next_level = dict()
                instance_level = dict()
                current_level[constraint_field.name] = instance_level
                instance_level[constraint_field] = next_level
                known_fields.append(constraint_field.name)
                current_level = next_level

            # if found a field, check if its instance has indeed been put in
            # before
            if found_field is not None:
                instances = current_level[constraint_field.name]
                if constraint_field in instances:
                    current_level = instances[constraint_field]
                elif constraint_field.value not in instances:
                    next_level = dict()
                    instance_level = dict()
                    instances[constraint_field] = instance_level
                    instances[constraint_field] = next_level
                    current_level = next_level

    @staticmethod
    def _add_field_constraints(partition, graph_mapper, partitionable_graph,
                               n_keys_map):
        """
        searches though the subgraph adding field constraints for the key
         allocator
        :param partition:
        :param graph_mapper:
        :param partitionable_graph:
        :return:
        """

        fields = list()

        verts = list(partitionable_graph.vertices)
        subvert = partition.edges[0].pre_subvertex
        vertex = graph_mapper.get_vertex_from_subvertex(subvert)
        subverts = list(graph_mapper.get_subvertices_from_vertex(vertex))

        # pop based flexi field
        fields.append(FlexiField(flexi_field_name="Population",
                                 value=verts.index(vertex),
                                 tag=SUPPORTED_TAGS.ROUTING.name))

        # subpop flexi field
        fields.append(FlexiField(
            flexi_field_name="SubPopulation{}".format(verts.index(vertex)),
            tag=SUPPORTED_TAGS.ROUTING.name,
            value=subverts.index(subvert)))

        fields.append(FlexiField(
            flexi_field_name="POP({}:{})Keys"
            .format(verts.index(vertex), subverts.index(subvert)),
            tag=SUPPORTED_TAGS.APPLICATION.name,
            instance_n_keys=n_keys_map.n_keys_for_partitioned_edge(
                partition.edges[0])))

        # add constraint to the subedge
        partition.add_constraint(KeyAllocatorFlexiFieldConstraint(fields))

    @staticmethod
    def _create_internal_field_space(higher_space, field_value, field):
        """

        :param higher_space:
        :param field_value:
        :param field:
        :return:
        """
        inputs = dict()
        inputs[field.name] = field_value
        return higher_space(**inputs)

    @staticmethod
    def _locate_field_by_name(feild_list, field_name):
        """

        :param feild_list:
        :param field_name:
        :return:
        """
        for field in feild_list:
            if field.name == field_name:
                return field
        return None