# Copyright (c) 2020 The University of Manchester
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This workflow will install Python dependencies, run tests, lint and rat with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Actions

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8]

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout SupportScripts
      uses: actions/checkout@v2
      with:
        repository: SpiNNakerManchester/SupportScripts
        path: support

    - name: Install pip, etc
      uses: ./support/actions/python-tools

    - name: Checkout Spinnaker Dependencies
      uses: ./support/actions/checkout-spinn-deps
      with:
        repositories: SpiNNUtils SpiNNMachine
        install: true
        preinstall: ${{ matrix.python-version == 2.7 }}

    - name: Setup
      uses: ./support/actions/run-setup
      with:
        preinstall: ${{ matrix.python-version == 2.7 }}

    - name: Test with pytest
      uses: ./support/actions/pytest
      with:
        tests: unittests
        coverage: ${{ matrix.python-version == 3.6 }}
        cover-packages: pacman
        coveralls-token: ${{ secrets.COVERALLS_REPO_TOKEN }}

    - name: Lint with pylint
      # This would be version-independent... except pylint finds different things in different Python versions
      uses: ./support/actions/pylint
      with:
        package: pacman

  validate:
    # These actions are only run on 3.6 as they are basically version-independent
    runs-on: ubuntu-20.04

    steps:
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout SupportScripts
      uses: actions/checkout@v2
      with:
        repository: SpiNNakerManchester/SupportScripts
        path: support

    - name: Install pip, etc
      uses: ./support/actions/python-tools
    - name: Checkout Spinnaker Dependencies
      uses: ./support/actions/checkout-spinn-deps
      with:
        repositories: SpiNNUtils SpiNNMachine
        install: true
    - name: Setup
      uses: ./support/actions/run-setup

    - name: Lint with flake8
      run: flake8 pacman pacman_integration_tests unittests uinit_test_objects

    - name: Run rat copyright enforcement
      uses: ./support/actions/check-copyrights

    - name: Validate all XML
      uses: ./support/actions/validate-xml
      with:
        base-path: pacman

    - name: Build documentation with sphinx
      uses: ./support/actions/sphinx
      with:
        directory: doc/source
